"""Add national_id and other fields to Client

Revision ID: 788ba0e1d143
Revises: d05e1b287cf9
Create Date: 2025-04-26 18:10:48.588911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788ba0e1d143'
down_revision = 'd05e1b287cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('national_id', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('birth_certificate', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('county', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('subcounty', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('village', sa.String(length=100), nullable=False))
    op.alter_column('clients', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'contact_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('clients', 'village')
    op.drop_column('clients', 'subcounty')
    op.drop_column('clients', 'county')
    op.drop_column('clients', 'country')
    op.drop_column('clients', 'birth_certificate')
    op.drop_column('clients', 'national_id')
    # ### end Alembic commands ###
